### ISSUE TITLE
(some) certificates lack a description yielding an empty select box in the 2FA demo

### ISSUE THREAD

**Issue by netbrothers-tr** [Setasign/SetaPDF-Signer-Addon-Globaltrust-Trust2Go#6]
[In the 2FA demo](https://github.com/Setasign/SetaPDF-Signer-Addon-Globaltrust-Trust2Go/blob/585cb1c1533c1500e22670ef411d49874443b342/examples/2fa-demo/index.html#L151) you may end up with unnamed options in the certificate drop-down, rendering them invisible. This is due to the fact, that the `description` property of the returned certificates may be an empty string.

Unfortunately, this is not documented by TRUST2GO, but can be circumvented by naming the options with a combination of the `certificateSerialNumber` property and, if present, the `description`, like so.

```js
let opt = '<option value="' + certificate.certificateSerialNumber + '">{{NAME}}</option>';
let name = certificate.certificateSerialNumber;
if (certificate.description) {
    name += ' (' + certificate.description + ')';
}
certificatesHtml += opt.replace('{{NAME}}', name);
```
From our experience, it's the user level certificates (the relevant ones) that do not have a description, whereas root and sub level certificates have one.

**Comment by MaximilianKresse** [comment]
We just updated the 2FA demo. We now use an external library to parse the certificate and fetch the common name from the subject.

**Comment by netbrothers-tr** [comment]
Sounds good, @MaximilianKresse! It worked for me.
