### ISSUE TITLE
presign method provokes SetaPDF_Core_Type_IndirectReference_Exception

### ISSUE THREAD

**Issue by netbrothers-tr** [Setasign/SetaPDF-Signer-Addon-Globaltrust-Trust2Go#7]
While fiddling with the [2FA demo](https://github.com/Setasign/SetaPDF-Signer-Addon-Globaltrust-Trust2Go/tree/main/examples/2fa-demo), we ran into the following exception.

```
Fatal error: Uncaught SetaPDF_Core_Type_IndirectReference_Exception: Object could not be resolved (15, 0) in <REDACTED>/vendor/setasign/setapdf-signer_eval_ioncube_php7.1/library/SetaPDF/Core/Type/IndirectReference.php:172 Stack trace: 
#0 <REDACTED>/vendor/setasign/setapdf-signer_eval_ioncube_php7.1/library/SetaPDF/Core/Document.php(1839): SetaPDF_Core_Type_IndirectReference->ensure() 
#1 <REDACTED>/vendor/setasign/setapdf-signer_eval_ioncube_php7.1/library/SetaPDF/Core/Document.php(1506): SetaPDF_Core_Document->_updateFileIdentifier() 
#2 <REDACTED>/vendor/setasign/setapdf-signer_eval_ioncube_php7.1/library/SetaPDF/Signer.php(774): SetaPDF_Core_Document->save() 
#3 <REDACTED>/vendor/setasign/setapdf-signer_eval_ioncube_php7.1/library/SetaPDF/Signer.php(598): SetaPDF_Signer->_prepareTemporaryVersion() 
#4 <REDACTED>/public/controll in <REDACTED>/vendor/setasign/setapdf-signer_eval_ioncube_php7.1/library/SetaPDF/Core/Type/IndirectReference.php on line 172

```

We figured, that it is provoked by the [`presign()`-method](https://github.com/Setasign/SetaPDF-Signer-Addon-Globaltrust-Trust2Go/blob/585cb1c1533c1500e22670ef411d49874443b342/examples/2fa-demo/controller.php#L68) of the `SetaPDF_Signer` and it seems to be happening in connection with writing a temporary file. For this reason, we've changed the `sys_temp_dir` PHP option and set generous directory permissions. In any case, the file gets written and has the typical structure of a PDF file. Hence writing the file doesn't seem to be the problem. Since the stack trace mentions `_updateFileIdentifier()`, we wonder if there is anything unusual happening after writing the file and how the environment needs to be configured for this to work properly.

Some specs:

- PHP 7.4.30 (FPM/FastCGI)
- Apache 2.4.54
- Ubuntu 22.04.1 LTS

**Comment by JanSlabon** [comment]
Can you share the PDF in question?
This simply looks like a faulty PDF. Or are you writing to a file you are reading from?

**Comment by netbrothers-tr** [comment]
Thank you, @JanSlabon, for the hint. After using [this sample PDF from w3.org](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf) it worked flawlessly, thus closing the issue.

Are there any simple and common checks we can do with the files, before we allow them to be signed? The faulty PDF was this one: [dummy.pdf](https://github.com/Setasign/SetaPDF-Signer-Addon-Globaltrust-Trust2Go/files/9422873/dummy.pdf).

**Comment by JanSlabon** [comment]
Okay, we fixed this type of issue in the Core component. This problem can be ignored and the document is absolutely fine.
In general there's no way to forsee if a PDF is valid at all levels. This can only be done by processing it completely.

**Comment by netbrothers-tr** [comment]
Okay, thanks. Good to know, it wasn't the document's fault. :wink:
